---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crdb.oggy.haugland.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crdb.oggy.haugland.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - crdb.oggy.haugland.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crdb.oggy.haugland.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crdb.oggy.haugland.io
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - crdb.oggy.haugland.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
